### ISSUE TITLE
🐛 foot-server.service doesn't run a login shell

### ISSUE THREAD

**Issue by mesmere** [Manjaro-Sway/manjaro-sway#721] opened 2024-03-06 20:25 UTC
### branch

stable

### Architecture

x86_64

### Description

Normally when you run a foot terminal it inherits environment variables set in e.g. `.profile` because greetd [sources `$HOME/.profile`](https://git.sr.ht/~kennylevinsen/greetd/tree/master/item/greetd/src/session/worker.rs#L234) just before running the sway command.

However, the foot-server.service systemd unit doesn't benefit from this, and any shells launched with `footclient` will be missing profile stuff.

### Reproduction steps

My use-case is that I have a binding to open up floating terminal windows:

```bash
$bindsym $mod+Shift+Return exec $term_float
```

But you could also just run `footclient` from a terminal:

```
footclient --app-id floating_shell --window-size-chars 82x25
```

Observe that the shell has never had `.profile` stuff run. E.g.

```
echo $EDITOR
```

...should be nvim but it's empty. I have other stuff set up too like nodenv shims which don't work in floating terminals for this reason.

**Comment by boredland** [comment] 2024-03-06 22:30
If it already works with adding that `-L` flag to footclient - why do you think it needs to be added to the server too?

**Comment by boredland** [comment] 2024-03-06 23:38
I think there's even a more general issue. If _no_ userspace foot.ini is provided, I don't this the fallback works. I pushed an idea that involves an override for the systemd unit.

You could try `manjaro-sway-settings-git` in a few. [This](https://github.com/manjaro-sway/desktop-settings/commit/27d18950d764abdb45ff78dea12eae8dda5f946e) is the commit.

**Comment by boredland** [comment] 2024-03-07 00:34
For some reason nmtui doesn't open from the waybar anymore. Currently out of ideas.

**Comment by boredland** [comment] 2024-03-07 08:52
So, fresh morning, fresh mind: Apparently nmtui doesn't start in a Login-Shell. Compare `footclient -L nmtui connect` vs `footclient nmtui connect`. Therefor I reverted to only setting `-L` on the footclient, not the server. Does this solve your problem? Should be pushed to `manjaro-sway-settings-git`.

**Comment by boredland** [comment] 2024-03-07 14:33
This means we can't do 1., because we'd wouldn't have an opt-out for nmtui, right?

**Comment by boredland** [comment] 2024-03-09 10:35
But with the 2. option, users would have all the benefits, if the spawn a new terminal window e.g. using Super+Enter, no?

**Comment by boredland** [comment] 2024-03-10 15:25
I think the initial issue was, that the .profile declarations loaded by greetd not being available in foot, is fixed by loading the system unit at the correct time. this is fixed by slight modifications in the dependencies of the systemd-unit. there is _another_ and maybe related issue, #725: while `export abc=def` in `.profile` and `.config/profile.d/*` works as intended, aliases aren't available in foot. could be an issue in the zsh-setup - will surely take a look. anyway: will make a minor release and close this for now.

**Closed as completed by boredland** 2024-03-10 15:25 UTC
Labels: bug
