### ISSUE TITLE
/waybar/config.jsonc "on-click": "swaymsg exec... does not work

### ISSUE THREAD

**Issue by durito28** [manjaro-sway/manjaro-sway#566] opened 2023-07-22 16:29 UTC
### branch

stable

### Architecture

x86_64

### Description

hello,
currently the open with "one-click" from waybar does not work for me anymore (only chlipboard works). The exact start of the malfunction I have unfortunately not noticed...maybe since about 2 weeks.

To my surprise "one-klick" with live-usb works on my old laptop, but not on my current one (Thinkpad T470p).

Does anyone have an idea how I can fix the error or what the cause is

### Reproduction steps

```bash
sudo pacman -Syyu manjaro-sway-settings
skel
```

**Comment by boredland** [comment] 2023-07-22 22:50
What is the one-click waybar?

**Comment by durito28** [comment] 2023-07-23 12:18
Excuse my inaccurate English:

I mean for example the command (/home/.../.config/waybar/config.jsonc) 

"on-click": "swaymsg exec \\$once \\$term_float nmtui connect".

This has no effect and opens no window

**Comment by boredland** [comment] 2023-07-23 16:21
For me it opens just fine.

**Comment by durito28** [comment] 2023-07-23 16:42
I haven't found the reason yet either. 

If I change the line
"on-click": "swaymsg exec \$once \$term_float nmtui connect"

to

"on-click": "swaymsg exec \$once \$term nmtui connect"

it works (but not nice for me)

apparently the part "\\$term_float " does not work for me

**Comment by hakanyi** [comment] 2023-07-25 20:52
Same here. 
It seems like foot doesn't like fractional scaling: 

```
/usr/share/sway/scripts/foot.sh --server                                                                 ✔  19s  
warn: wayland.c:1454: fractional scaling not available                                                                          
warn: wayland.c:1462: no server-side cursors available, falling back to client-side cursors
```

And without a running foot server, invoking `$term_float` does not work as it uses `footclient`

**Comment by boredland** [comment] 2023-07-28 21:36
Could you both provide the native resolution and the scaling this happens with? I am struggling to reproduce.

**Comment by Galbar** [comment] 2023-07-29 20:54
I'm having the same issue. Nothing happens when I click on the icons in the waybar. Programs still work when I run them manually on a terminal.

How can I help debug this issue?

**Comment by boredland** [comment] 2023-07-29 22:15
Ah, I should have reported back here. Can you try if installing `foot-git` from the AUR does the trick for you? There is an issue with fractional scaling and the sizing by lines we use for the floating windows, that seems to be resolved in the current development version of foot.

**Comment by boredland** [comment] 2023-07-30 07:36
My assumption is, that this will be fixed with the next `foot` release or by using a "round" fractional scaling value.

**Closed by boredland** 2023-07-30 07:36 UTC
Labels: bug
