### ISSUE TITLE
greetd-tuigreet, maximum file size exceeded from packages.manjaro-sway.download

### ISSUE THREAD

**Issue by bdefore** [Manjaro-Sway/manjaro-sway#211] opened 2022-01-03 04:18 UTC
I receive the following error when trying to update today via yay:

```
:: Retrieving packages...
 greetd-tuigreet-0.7.1-2-x86_64.pkg.tar.zst failed to download
 Total (  1/210)                              51.8 MiB  1295 MiB/s 00:00 [########################################] 100%
error: failed retrieving file 'greetd-tuigreet-0.7.1-2-x86_64.pkg.tar.zst' from packages.manjaro-sway.download : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
```

May be related: https://github.com/Manjaro-Sway/manjaro-sway/issues/200

**Comment by boredland** [comment] 2022-01-03 07:24
ya seems I borked the db file again. will try to fix that.

**Comment by boredland** [comment] 2022-01-03 07:27
will take the chance to try to move all of it to git-lfs again

**Comment by boredland** [comment] 2022-01-03 08:10
ya lfs will [never work with pages](https://github.com/git-lfs/git-lfs/issues/3498)

**Comment by boredland** [comment] 2022-01-03 08:31
reverted everything.

**Comment by Galbar** [comment] 2022-01-03 21:04
I'm still getting this error message. Is there anything specific I should be doing to have the fix it?

**Comment by boredland** [comment] 2022-01-03 21:09
I wouldn't know why. For me it works:

```
$ sudo pacman -Syyu greetd-tuigreet
Place your right index finger on the fingerprint reader
:: Synchronizing package databases...
 core                                                                  169,4 KiB  1540 KiB/s 00:00 [##########################################################] 100%
 extra                                                                1916,4 KiB  17,0 MiB/s 00:00 [##########################################################] 100%
 community                                                               6,8 MiB  26,9 MiB/s 00:00 [##########################################################] 100%
 multilib                                                              178,2 KiB  4,05 MiB/s 00:00 [##########################################################] 100%
 manjaro-sway                                                           19,0 KiB   136 KiB/s 00:00 [##########################################################] 100%
warning: greetd-tuigreet-0.7.1-2 is up to date -- reinstalling
:: Starting full system upgrade...
warning: oh-my-zsh: local (r6072.c44b99e90-1) is newer than community (r5951.86f805280-1)
resolving dependencies...
looking for conflicting packages...

Packages (1) greetd-tuigreet-0.7.1-2

Total Installed Size:  3,07 MiB
Net Upgrade Size:      0,00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                     [##########################################################] 100%
(1/1) checking package integrity                                                                   [##########################################################] 100%
(1/1) loading package files                                                                        [##########################################################] 100%
(1/1) checking for file conflicts                                                                  [##########################################################] 100%
(1/1) checking available disk space                                                                [##########################################################] 100%
:: Running pre-transaction hooks...
(1/1) Creating Timeshift snapshot before upgrade...
==> skipping timeshift-autosnap due skipRsyncAutosnap in /etc/timeshift-autosnap.conf set to TRUE.
:: Processing package changes...
(1/1) reinstalling greetd-tuigreet                                                                 [##########################################################] 100%
ldconfig: File /usr/lib/libgeos-3.9.1.so is empty, not checked.
ldconfig: File /usr/lib/libgeos.so is empty, not checked.
:: Running post-transaction hooks...
(1/2) Creating temporary files...
(2/2) Arming ConditionNeedsUpdate...
```

**Comment by Galbar** [comment] 2022-01-03 21:34
When I try using `pamac` I get this output:
```
Preparing...
Synchronizing package databases...
Resolving dependencies...
Checking inter-conflicts...
Download of greetd-tuigreet (0.7.1-2) started
Download of greetd-tuigreet (0.7.1-2) finished
Checking keyring...
Checking integrity...
Error: greetd-tuigreet: signature from "Jonas Strassel <info@jonas-strassel.de>" is invalid
Removing invalid files and retrying...
Resolving dependencies...
Checking inter-conflicts...
Download of greetd-tuigreet (0.7.1-2) started
Download of greetd-tuigreet (0.7.1-2) finished
Checking keyring...
Checking integrity...
Error: greetd-tuigreet: signature from "Jonas Strassel <info@jonas-strassel.de>" is invalid
Failed to commit transaction:
invalid or corrupted package (PGP signature):

```
This is what I get running it from the terminal:

```bash
sudo pacman -Syyu greetd-tuigreet                                                                                                                                                                                                              

:: Synchronizing package databases...
 core                                         169,4 KiB   330 KiB/s 00:01 [################################################################] 100%
 extra                                       1916,4 KiB  1467 KiB/s 00:01 [################################################################] 100%
 community                                      6,8 MiB   898 KiB/s 00:08 [################################################################] 100%
 multilib                                     178,2 KiB  2,17 MiB/s 00:00 [################################################################] 100%
 manjaro-sway                                  19,0 KiB   112 KiB/s 00:00 [################################################################] 100%
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) greetd-tuigreet-0.7.1-2

Total Download Size:   1,14 MiB
Total Installed Size:  3,07 MiB
Net Upgrade Size:      0,00 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 greetd-tuigreet-0.7.1-2-x86_64.pkg.tar.zst failed to download
error: failed retrieving file 'greetd-tuigreet-0.7.1-2-x86_64.pkg.tar.zst' from packages.manjaro-sway.download : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
```

**Comment by Galbar** [comment] 2022-01-03 21:39
Weird, it looks like the newer version is installed?
```
$ pamac search greetd                                                                                                                                                                                                                  
greetd-tuigreet                                                                                                                                                                                                              [Installed] 0.7.1-2  manjaro-sway 
    A console UI greeter for greetd
greetd                                                                                                                                                                                                                       [Installed] 0.7.0-1  community 
    Generic greeter daemon
```

But it still shows like it needs an update?
![image](https://user-images.githubusercontent.com/3595851/147983218-e3357417-5988-4a44-a556-a1f164778e82.png)

**Comment by gregorbg** [comment] 2022-01-04 12:59
Just leaving a note here that I'm still running into this issue, despite `sudo pacman -Syyu` refresh.
Symptoms are exactly identical to what @Galbar describes.

**Comment by gregorbg** [comment] 2022-01-04 13:04
Observation: Manually downloading the `.pkg.tar.zst` (and corresponding `.sig` file) and then installing via `pacman -U` works.

**Comment by humb1t** [comment] 2022-01-04 18:36
@gregorbg thank you - manual download and update option worked great!

**Comment by boredland** [comment] 2022-01-04 20:54
I think there is still some breakage in the .db file. Will try and iterate the tuigreet pkgrel, since that should "replace" it.

**Comment by boredland** [comment] 2022-01-04 21:12
soo, for me an update went up and through. hope for you too? closing this again for now.

**Closed by boredland** 2022-01-04 21:12 UTC

**Comment by Galbar** [comment] 2022-01-04 21:42
I can confirm that the new update worked well for me

**Comment by gregorbg** [comment] 2022-01-05 07:53
Confirmed, new update `0.7.1-4` has worked. Thanks for resolving this issue very quickly :smile:
