### ISSUE TITLE
Username and password don't work

### ISSUE THREAD

**Issue by Zeioth** [Manjaro-Sway/manjaro-sway#140] opened 2021-08-21 22:43 UTC
I booted the live CD for the build of 21AGO/2021 and I get this screen while the livecd loads. But the username and password is not manjaro.

Is this a bug? What's the latest working build I can use? Thank you.

![20210822_004359](https://user-images.githubusercontent.com/3357792/130336583-be83d64f-919d-4c75-8bbf-2155bf959d3d.jpg)

**Comment by boredland** [comment] 2021-08-21 22:50
are you on a real machine or in vmware/vbox?

**Comment by boredland** [comment] 2021-08-21 22:52
1. change the cmd (F2) to zsh
2. login using manjaro/manjaro
3. run 'sway' check the output

**Comment by boredland** [comment] 2021-08-21 22:57
likely an overlap with https://github.com/Manjaro-Sway/manjaro-sway/issues/139

**Comment by Zeioth** [comment] 2021-08-21 23:00
Real machine. Following your instructions:
![20210822_010017](https://user-images.githubusercontent.com/3357792/130336857-b4439a13-b22f-449c-b27b-e5919547f5a0.jpg)

**Comment by boredland** [comment] 2021-08-21 23:10
hm, perhaps you can try it with `sway -d`

**Comment by Zeioth** [comment] 2021-08-21 23:13
A get a bit more verbose that way
![20210822_011224](https://user-images.githubusercontent.com/3357792/130337056-b466a85c-d406-41c2-a481-28c9877ad39d.jpg)

**Comment by boredland** [comment] 2021-08-21 23:24
sorry to say, but since I have no way to reproduce, I guess you have to find out why sway isn't finding a gpu on your machine..
do the hints from https://github.com/swaywm/sway/issues/4868 or https://github.com/swaywm/sway/issues/4672 help?

**Comment by press5** [comment] 2021-08-21 23:47
@Zeioth I noticed the error `Failed to open any DRM device`.  This suggests you might need a proprietary video driver loaded that you currently don't.

**Comment by Zeioth** [comment] 2021-08-21 23:58
May be. I'm trying with nouveau.

I'm trying to manually pass my GPU with
WLR_DRM_DEVICES=/dev/dri/card0:/dev/dri/card1 sway

But the dri directory doesn't exist.

**Comment by Zeioth** [comment] 2021-08-22 00:02
Ok I'm fucking retarded: I accidentally choose the privative drivers in the splash window.

Now I reboot and choose the open source drivers and I'm getting black screen. Maybe I can sort this out.

**Comment by Zeioth** [comment] 2021-08-22 00:10
I noticed I can ACTUALLY see the desktop for a moment, but the mouse is frozen and it goes blank moments after

https://youtu.be/N0ZQ3CpANl4

**Comment by boredland** [comment] 2021-08-22 00:13
you can try the manual start like above and look if there's more and different output now

**Comment by boredland** [comment] 2021-08-22 01:10
You can just append it to /etc/environment

**Comment by Zeioth** [comment] 2021-08-22 01:32
If you add it to the next build I can try it like, super fast. 

I have no access to that login menu anymore now that I'm loading nouveau.

**Comment by boredland** [comment] 2021-08-22 01:35
> I have no access to that login menu anymore now that I'm loading nouveau.

Can't you switch tty then? Like `CTRL+ALT+F-Key`.

**Comment by Zeioth** [comment] 2021-08-22 01:38
For some reason it doesn't spawn the tty as it should :(

**Comment by Zeioth** [comment] 2021-08-22 02:23
The fixes seem to have been merged into nouveau, but idk if they are already into manjaro stable branch. Probably not.
https://github.com/swaywm/sway/wiki#sway-16-shows-garbage-or-a-blank-screen-on-nouveau

**Comment by Zeioth** [comment] 2021-08-22 02:36
Either having a build with the env var and/or the latest non LTS kernel, should do the trick by now for nouveau users.

**Comment by boredland** [comment] 2021-08-22 08:58
> Either having a build with the env var and/or the latest non LTS kernel, should do the trick by now for nouveau users.

new images should build with both now - hang in there. should be uploaded in 40m.

**Comment by boredland** [comment] 2021-08-22 09:34
voilà: https://github.com/Manjaro-Sway/manjaro-sway/releases/tag/202108220857

**Comment by Zeioth** [comment] 2021-08-22 16:06
Thank you for having it ready so fast!!
I burned the 5.14, but it doesn't seem to do the trick. After "Livemedia CD script" during the boot the screen goes blank still.
I'm gonna try with the 5.10 just in case.

If that doesn't work I'll just wait a couple weeks until I can hopefuly buy an amd GPU.

**Comment by Zeioth** [comment] 2021-08-22 16:55
Nah, same result. I'm clueless then.

**Comment by Zeioth** [comment] 2021-08-22 16:57
Even the monitor turns off.

**Comment by Zeioth** [comment] 2021-08-22 18:35
Sorry for bothering but I think my card (Nvidia 1070) might just not be compatible with nouveau, as I'm trying to boot Manjaro i3 live CD and I get exactly the same problem.

**Comment by boredland** [comment] 2021-08-25 10:57
closing, since I don't have such a modern nvidia card. it worked in the past on a lenovo p52 with nouveau. I will add a warning to our readme.

**Closed by boredland** 2021-08-25 10:57 UTC
